DELETE_MESSAGE_AFTER_IN_SEC = 5
FINISH_MATCH_AFTER_IN_SEC = 5#60 * 10 # 10 Minutes
DELETE_MATCH_TIMEOUT_IN_SEC = 60 * 60 * 5 # 5 Hours
MATCH_CHANNEL_NAME_START = "matches-lobby"
MATCH_CHANNEL_NAME_END = ""